riscv64: replace deprecated legacy extensions to SBI 2.0 extensions
hermit-os/kernel pull request #1088
Opened 2024-03-03 07:36 UTC by luojia65

The SBI legacy extensions are deprecated 4 years ago ( https://github.com/riscv-non-isa/riscv-sbi-doc/commit/705e9556d25dc070926b99f8ccbcdc5073407447 ). We replace it using functions from SBI 2.0 extensions. Specifically:
- the legacy console_putchar is replaced into console_write_byte in SBI DBCN extension;
- legacy shutdown is replaced to system_reset in SBI SRST extension with ColdReboot and NoReason as parameters;
- legacy set_timer is replaced with SBI TIME set_timer;
- legacy send_ipi is replaced to SBI IPI extension. The code implemented in file processor.rs creates a HartMask with only one hart_id selected as an IPI target.

By updating to SBI 2.0, this commit supports to send IPI to hart IDs greater than 63 (on 64-bit devices). The current code encodes hart_id parameter in bit-vector like `1 << hart_id`, which will cause the bit to be shifted out from `usize` range when `hart_id >= 64`. SBI 2.0 fixed this problem by adding a `hart_mask_base` parameter, allowing us to specify any hart ID within `usize` range when is provided as an SBI IPI hart mask.

2024-03-13 17:45 UTC, mkroening requested changes
This might be an issue with QEMU again, but we are experiencing crashes in CI. 🤔

2024-04-16 17:26 UTC, mkroening requested changes
I updated the loader and OpenSBI.

We are having reboots, though.

2024-04-17 02:26 UTC, luojia65 commented on src/arch/riscv64/kernel/processor.rs
> +			sbi_rt::system_reset(sbi_rt::ColdReboot, sbi_rt::NoReason);
Oh, we'd replace to sbi_rt::Shutdown here :)

2024-04-17 07:06 UTC, mkroening commented on src/arch/riscv64/kernel/processor.rs
> +			sbi_rt::system_reset(sbi_rt::ColdReboot, sbi_rt::NoReason);
Thanks, but `Reset` does not work (CI does not pass). I think it should be `Shutdown`.

Also, you can squash your commits. I can also do this before merging, if you prefer that, though. :)

2024-04-17 07:41 UTC, luojia65 commented on src/arch/riscv64/kernel/processor.rs
> +			sbi_rt::system_reset(sbi_rt::ColdReboot, sbi_rt::NoReason);
Fixed :) Thanks for noting that out! I'll squash the commits.

2024-04-17 09:26 UTC, mkroening approved these changes
Thanks a lot! And thanks for being patient! :)

2024-04-17 09:37 UTC, merged