Use hypercall definitions from uhyve-interface
hermit-os/kernel pull request #1393
Opened 2024-09-20 08:36 UTC by jounathaen

This depends on https://github.com/hermit-os/uhyve/pull/757 (and a publication of uhyve interface V0.1.2)

This is the final step of putting the hypercall definitions in a central crate.
This PR should just deduplicate code without changing functionality.

2024-10-31 18:09 UTC, jounathaen commented
Depends on #1442

2024-11-25 19:17 UTC, stlankes approved these changes

2024-11-26 10:41 UTC, mkroening requested changes
Overall, this looks good to me, but I have a few remarks. :)

2024-11-26 10:41 UTC, mkroening commented on src/syscalls/interfaces/uhyve.rs
>  }
Why not share a common function definition across architectures like before?

2024-11-26 10:41 UTC, mkroening commented on src/syscalls/interfaces/uhyve.rs
> +fn data_addr<T>(data: &T) -> u64 {
Nit regarding all doc comments: the doc comments should come before attributes. Also, the beginning of doc comments should be capitalized.

2024-11-26 10:41 UTC, mkroening commented on src/fs/uhyve.rs
> +		uhyve_hypercall(Hypercall::FileClose(&mut close_params));
Should we resolve this TODO before merging the PR?

2024-11-26 10:41 UTC, mkroening commented on Cargo.lock
`Cargo.lock` should be updated separately. I have opened https://github.com/hermit-os/kernel/pull/1474.

2024-12-17 18:16 UTC, jounathaen commented
I hope the latest version has addressed all your comments :slightly_smiling_face:

2024-12-31 11:21 UTC, mkroening approved these changes
Looks good to me! :)

Sorry for the wait!

2024-12-31 12:05 UTC, merged