Uhyve: Speed up serial output
hermit-os/kernel pull request #1468
Opened 2024-11-25 17:21 UTC by jounathaen

- Uhyve: Use the `SerialBufferWrite` hypercall instead of the `Uart` hypercall: This reduces the number of serial output related hypercalls by ~3x.

Attention:
- Depends on https://github.com/hermit-os/kernel/pull/1393
- Depends on a new Uhyve release that has support for this hypercall (v0.4.0)

2024-12-03 12:52 UTC, mkroening approved these changes
I don't feel good about including `heapless` since we have come so far without it, but I can't think of anything better. 👍 

Regarding the general approach, it would be a lot nicer to have a proper `io::BufWriter`, but `core::io` is too far away still. (The most up-to-date approach I could find is [wcampbell0x2a/no-std-io2](https://github.com/wcampbell0x2a/no-std-io2), and even that has issues.

So leaving `io::BufWriter` aside, it might still be worthwhile to have this buffering strategy take place outside `arch` such that all serial ports can take advantage of it. For those that can't, the overhead will probably not be too bad, I think. Avoiding the `\n` check here by extracting this into external `flush` calls would also be nice sometime in the future when we have nice `core::io` abstractions.

2024-12-03 12:55 UTC, jounathaen commented
I agree with all your points.  Especially, the unification of some IO functions across the architectures is desirable. But I'd still propose to merge this now and enhance later on.

2024-12-03 13:11 UTC, mkroening commented
> But I'd still propose to merge this now and enhance later on.

Yeah, sure, but this is blocked on https://github.com/hermit-os/kernel/pull/1393.

2024-12-31 23:21 UTC, mkroening requested changes
Could you rebase this, since https://github.com/hermit-os/kernel/pull/1393 is merged? :)

2025-01-13 14:21 UTC, mkroening requested changes
Would it make sense to move this to the arch-independent part `Console` ([src/console.rs#L15-L17](https://github.com/hermit-os/kernel/blob/b2eef95abb4012cde30a8e1c47e5c67b3ad053e9/src/console.rs#L15-L17))?

That would drastically reduce the code duplication, make the code simpler, and avoid `clippy::large_enum_variant`. The additional overhead of doing an extra copy for byte-wise serial devices is probably negligible, I'd expect.

2025-01-13 17:18 UTC, mkroening requested changes
The output of the second commit is wrong. I'll look for the new line issue tomorrow.

2025-01-14 09:15 UTC, mkroening requested changes

2025-01-14 09:37 UTC, mkroening approved these changes

2025-01-14 10:41 UTC, merged