return error also in the closing state
hermit-os/kernel pull request #881
Opened 2023-09-02 07:36 UTC by stlankes

If smoltcp receives a FIN message, the socket changes the state to the `closing`, but the socket is still active. To close the socket, the kernel returns a error if the socket is in the closing state.

The PR should solve issue hermit-os/kernel#880

2023-09-02 18:32 UTC, mkroening requested changes
I think we should return `Ok(0)` in both cases.

From [`Read::read`](https://doc.rust-lang.org/nightly/std/io/trait.Read.html#tymethod.read):

> If n is 0, then it can indicate one of two scenarios:
>
> 1.   This reader has reached its “end of file” and will likely no longer be able to produce bytes. Note that this does not mean that the reader will always no longer be able to produce bytes. As an example, on Linux, this method will call the recv syscall for a [TcpStream](https://doc.rust-lang.org/nightly/std/net/struct.TcpStream.html), where returning zero indicates the connection was shut down correctly. While for [File](https://doc.rust-lang.org/nightly/std/fs/struct.File.html), it is possible to reach the end of file and get zero as result, but if more data is appended to the file, future calls to read will return more data.
> 2.    The buffer specified was 0 bytes in length.

From [`Write::write`](https://doc.rust-lang.org/nightly/std/io/trait.Write.html#tymethod.write):

> A return value of Ok(0) typically means that the underlying object is no longer able to accept bytes and will likely not be able to in the future as well, or that the buffer provided is empty.

Note that the example from the issue does not result in an error on Linux either.

2023-09-03 18:36 UTC, stlankes commented
You are right. I fixed if.

2023-09-04 08:18 UTC, mkroening requested changes
Should we really return an error on FIN-WAIT-1 etc.? It might be better to not match against the TCP state directly and instead use `may_send` and `may_receive`. What do you think?

https://github.com/smoltcp-rs/smoltcp/blob/main/examples/httpclient.rs#L84-L119

2023-09-04 08:34 UTC, mkroening approved these changes

2023-09-04 08:46 UTC, merged